#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MARKETPLACE_PATH="$SCRIPT_DIR/marketplace"

echo "======================================"
echo "  dotfiles-claude Installation"
echo "======================================"
echo ""
echo "This repository contains a Claude Code plugin with:"
echo "  - 5 skills (push-changes, manage-worktrees, skill-creator, heal-skill, create-agents-md)"
echo "  - 5 commands (/push, /worktree, /heal-skill, /create-skill, /claude-md)"
echo ""
echo "To install, run these commands in a Claude Code session:"
echo ""
echo "  /plugin marketplace add $MARKETPLACE_PATH"
echo "  /plugin install justin-tools@dotfiles-claude"
echo ""
echo "After installation, restart Claude Code to use the new plugin."
echo ""
echo "======================================"
echo "  Available Commands After Install"
echo "======================================"
echo ""
echo "  /push          - Stage, commit, and push with conventional messages"
echo "  /worktree      - Manage git worktrees for parallel development"
echo "  /heal-skill    - Analyze and fix skills that caused confusion"
echo "  /create-skill  - Create or convert Claude Code skills"
echo "  /claude-md     - Generate CLAUDE.md for current project"
echo ""
echo "======================================"
